import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'Next Blog',
    template: '%s | Next Blog',
  },
  description: 'Generated by create next app',
};

type AdminLayoutProps = {
  children: React.ReactNode;
};

export default function AdminLayout({ children }: AdminLayoutProps) {
  return <>{children}</>;
}
