import type { Metadata } from 'next';
import './globals.css';
import { ContainerComponent } from '@/components/Container';
import { HeaderComponent } from '@/components/Header';
import { FooterComponent } from '@/components/Footer';
import { NavigationMenu } from '@/components/NavigationMenu';
import { Suspense } from 'react';
import { LoadingSpinner } from '@/components/LoadingSpinner';

export const metadata: Metadata = {
  title: {
    default: 'Next Blog',
    template: '%s | Next Blog',
  },
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="pt-BR">
      <body>
        <ContainerComponent>
          <HeaderComponent />
          <Suspense fallback={<LoadingSpinner />}>
            <NavigationMenu />
          </Suspense>
          {children}
          <FooterComponent />
        </ContainerComponent>
      </body>
    </html>
  );
}
