import type { Metadata } from 'next';
import './globals.css';
import { ContainerComponent } from '../components/Container';
import { HeaderComponent } from '../components/Header';
import { FooterComponent } from '../components/Footer';

export const metadata: Metadata = {
  title: {
    default: 'Next Blog',
    template: '%s | Next Blog',
  },
  description: 'Generated by create next app',
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="pt-BR">
      <body>
        <ContainerComponent>
          <HeaderComponent />
          {children}
          <FooterComponent />
        </ContainerComponent>
      </body>
    </html>
  );
}
