import { requireLoginSessionOrRedirect } from '@/lib/login/manage-login';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'Next Blog',
    template: '%s | Next Blog',
  },
  description: 'Generated by create next app',
};

type AdminPostLayoutProps = {
  children: React.ReactNode;
};

export default async function AdminPostLayout({
  children,
}: AdminPostLayoutProps) {
  return <>{children}</>;
}
